### PR TITLE
Make runCommand compatible with MongoDB 6.0 (fixes #143)

### LINKED ISSUE #143: doesn't work on MongoDB 6.0
The current version is unable to authenticate on MongoDB 6.0. I thought the cause is the end of support for SCRAM-SHA-1, but it's not the only reason; apparently there is a significant change in the authentication protocol, but I wasn't able to figure out what exactly changed.

Here's my patch which adds support for SCRAM-SHA-256, however it fails in the first step due to the following error:

```
[ ok: 0, errmsg: "(Unauthorized) not authorized on admin to execute command { find: \"$cmd\", filter: { saslStart: 1, mechanism: \"SCRAM-SHA-256\", payload: \"biwsbj13ZWZpdCxyPXgzcHBzZitSUTBuWWJ5YkhlMHZ2bUE9PQ==\", autoAuthorize: 1 }, batchSize: 1, limit: 1, $db: \"admin\", projection: {  } }", code: 8000, codeName: "AtlasError"]
```

https://github.com/fumieval/mongodb/commit/6e79777656b058649acc055e9b3267d1c6140944

### PR DESCRIPTION
**Pull request by fumieval**
I confirmed that `auth` works both on MongoDB 5.0 and MongoDB 6.0

### CODE REVIEW

**Comment by fumieval** [comment]
@VictorDenisov Do you have a chance to take a look at this?

**Comment by VictorDenisov** [comment]
I remember about this PR. It's just last several weeks have been a bit hectic. I'll review it in the coming weeks. Sorry for delay.

**Comment by fumieval** [comment]
No rush. Thank you!

**Comment by kfiz** [comment]
Does authentication work if you add `saslStart` to this list https://github.com/mongodb-haskell/mongodb/blob/35ee53abed98732eab3f69a67e029674b942a38b/Database/MongoDB/Query.hs#L1239 ?

**Comment by fumieval** [comment]
@kfiz No, that didn't work

**Comment by fumieval** [comment]
@VictorDenisov Did you have a chance to take a look at this PR?

**Comment by VictorDenisov** [comment]
Sorry. It's been crazy lately. Give me a couple of weekends to review it.

File: Database/MongoDB/Query.hs [hunk 1]
```diff
@@ -1272,9 +1272,9 @@ find q@Query{selection, batchSize} = do
         qr <- queryRequestOpMsg False q
         let newQr =
               case fst qr of
-                Req qry ->
-                  let coll = last $ T.splitOn "." (qFullCollection qry)
-                  in (Req $ qry {qSelector = merge (qSelector qry) [ "find" =: coll ]}, snd qr)
+                Req P.Query{..} ->
```
Comment (VictorDenisov) [inline Database/MongoDB/Query.hs:1275]: Is this hunk necessary? Seems to be doing the same as before? Probably a remnant from experimenting with the code?

File: Database/MongoDB/Query.hs [hunk 2]
```diff
@@ -1332,14 +1334,14 @@ findOne q = do
...
+                    Req P.Query{..} ->
+                      let coll = last $ T.splitOn "." qFullCollection
                           -- We have to understand whether findOne is called as
                           -- command directly. This is necessary since findOne is used via
                           -- runCommand as a vehicle to execute any type of commands and notices.
-                          labels = catMaybes $ map (\f -> look f $ qSelector qry) (noticeCommands ++ adminCommands) :: [Value]
+                          labels = catMaybes $ map (\f -> look f qSelector) (noticeCommands ++ adminCommands) :: [Value]
                       in if null labels
-                           then (Req $ qry {qSelector = merge (qSelector qry) [ "find" =: coll ]}, snd qr)
+                           then (Req P.Query {qSelector = merge qSelector [ "find" =: coll ], ..}, snd qr)
```
Comment (VictorDenisov) [inline Database/MongoDB/Query.hs:1344]: Seems to be another unnecessary hunk.

File: Database/MongoDB/Query.hs (hunk 1 above)
Comment (fumieval) [reply Database/MongoDB/Query.hs:1275]: This gets rid of the use of a partial record selector function (which would produce a warning). I think it's a good practice to avoid using record selector functions to sum types

Comment (VictorDenisov) [reply Database/MongoDB/Query.hs:1275]: I see. It would be better to have refactorings in a separate commit. But it's good for now.
